version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: wandr-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mapdata
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: wandr-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: wandr-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: wandr-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  mongodb_data:
